apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: greenleaf
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: change-me
  MYSQL_DATABASE: gardening_db
  MYSQL_USER: gardenuser
  MYSQL_PASSWORD: change-me
  DB_USER: gardenuser
  DB_PASSWORD: change-me
  DB_NAME: gardening_db
